#!/bin/bash
FRUITS=("APPLE","BANANA","ORANGE")

echo "first fruit test :$FRUITS[0]"
echo "first fruit is :${FRUITS[0]}"
echo "second fruit is :${FRUITS[1]}"
echo "third fruit is :${FRUITS[2]}"

echo "All Fruits: ${FRUITS[@]}"